### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by georgehanson** [midnite81/prowl#1]
Would it make sense to change the order of the parameters here? It looks like the constructor will attempt to automatically resolve the client and request factory if none is provided, the config is just an empty array.

Therefore, a consumer may want to be able to specify the config but have the package resolve the client and request factory. The user might prefer to do this:

```php
new Prowl($config);
```

as opposed to

```php
new Prowl(null, null, $config);
```

https://github.com/midnite81/prowl/blob/ad2ba1157ea91eeeab75537d61e4a7c0b3bebfd2/src/Prowl.php#L29

**Comment by midnite81** [comment]
I see your point, but there are a couple of factory methods one of which is`Prowl::create($config)` which will handle that, and it is the way I see most people using it.

**Comment by knash94** [comment]
Just stalking you and I noticed in the readme you created the object with the config being the first parameter

```php
// Using this method you can chain through to send the message directly.
$prowl = new Prowl($config); 
```
